name: cd-samples

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

env:
  NODE_MINVERSION: '20'

jobs:
  build-dotnet:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build dotnet Samples
        working-directory: ./samples/dotnet
        run: |
          dotnet build

  build-node:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        # NOTE: keep first entry in sync with env.NODE_MINVERSION
        node-version: [20, 'latest']

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Node dependencies
        run: npm ci

      - name: Run lint
        run: npm run lint

      - name: Build Node Copilot Studio client sample
        working-directory: ./samples/nodejs/copilotstudio-client/
        run: |
          npm ci
          npm run build

      - name: Build Node Copilot Studio client - React Webchat sample
        working-directory: ./samples/nodejs/copilotstudio-webchat-react/
        run: |
          npm ci
          npm run build

      - name: Build Node QuickStart
        working-directory: ./samples/nodejs/quickstart
        run: |
          npm ci
          npm run build

      - name: Build Node Cards Agent
        working-directory: ./samples/nodejs/cards/
        run: |
          npm ci
          npm run build

      - name: Build Node Skill Agent
        working-directory: ./samples/nodejs/copilotstudio-skill/
        run: |
          npm ci
          npm run build

      - name: Build Node LangChain Agent
        working-directory: ./samples/nodejs/langchain-multiturn/
        run: |
          npm ci
          npm run build

      - name: Build Node StreamingResponse Agent
        working-directory: ./samples/nodejs/azure-ai-streaming/
        run: |
          npm ci
          npm run build

      - name: Build Node Auto Signin Agent
        working-directory: ./samples/nodejs/auto-signin/
        run: |
          npm ci
          npm run build

      - name: Build Node OBO Agent
        working-directory: ./samples/nodejs/obo-authorization/
        run: |
          npm ci
          npm run build

      - name: Build Node Copilot SDK sample
        working-directory: ./samples/nodejs/copilot-sdk/
        run: |
          npm ci
          npm run build

      - name: Build Node Multi-Turn Prompt Agent
        working-directory: ./samples/nodejs/multi-turn-prompt/
        run: |
          npm ci
          npm run build
