name: cd-samples

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
  
      - name: Set up Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install Node dependencies
        run: npm install
        working-directory: ./samples

      - name: Build dotnet Samples
        working-directory: ./samples
        run: |
          dotnet build
      

      - name: Run lint
        run: npm run lint
        working-directory: ./samples

      - name: Build Node Copilot Studio client sample
        working-directory: ./samples/basic/copilotstudio-client/nodejs/
        run: |
          npm ci
          npm run build

      - name: Build Node Copilot Studio client - React Webchat sample
        working-directory: ./samples/basic/copilotstudio-webchat-react/
        run: |
          npm ci
          npm run build

      - name: build Node Empty Agent
        working-directory: ./samples/basic/empty-agent/nodejs/
        run: |
          npm ci
          npm run build
      
      - name: Build  Node Cards bot
        working-directory: ./samples/basic/cards/nodejs/
        run: |
          npm ci
          npm run build

      - name: Build  iamge Node Skill bot
        working-directory: ./samples/complex/copilotstudio-skill/nodejs/
        run: |
          npm ci
          npm run build
      
      - name: Build Node Weather Agent
        working-directory: ./samples/basic/weather-agent/nodejs/
        run: |
          npm ci
          npm run build

